Update pretty.yml

diff --git a/.github/workflows/pretty.yml b/.github/workflows/pretty.yml
--- a/.github/workflows/pretty.yml
+++ b/.github/workflows/pretty.yml
@@ -64,3 +64,36 @@ jobs:
             echo "File "$FILE" was not found.";
             exit 1
         fi
+
+    - name: Checking if there exists at least one build script
+      run: |
+        FILE=build.sh
+        if [ $(find . -name "$FILE" -mmin -5 | wc -l) -gt 0 ]; then 
+            echo "File "$FILE" was found.";
+            exit 0 
+        else 
+            echo "File "$FILE" was not found.";
+            exit 1
+        fi
+
+    - name: Checking if there exists at least one remote build script
+      run: |
+        FILE=rbuild.sh
+        if [ $(find . -name "$FILE" -mmin -5 | wc -l) -gt 0 ]; then 
+            echo "File "$FILE" was found.";
+            exit 0 
+        else 
+            echo "File "$FILE" was not found.";
+            exit 1
+        fi
+
+    - name: Checking if there exists at least one test script
+      run: |
+        FILE=test.sh
+        if [ $(find . -name "$FILE" -mmin -5 | wc -l) -gt 0 ]; then 
+            echo "File "$FILE" was found.";
+            exit 0 
+        else 
+            echo "File "$FILE" was not found.";
+            exit 1
+        fi
